import java.nio.file.Files
import java.nio.file.Paths
import java.nio.file.StandardCopyOption

buildscript {
	repositories {
		maven { url = 'https://maven.minecraftforge.net/' }
		maven { url = 'https://plugins.gradle.org/m2' }
		mavenCentral()
	}

	dependencies {
		classpath('com.anatawa12.forge:ForgeGradle:1.2-1.0.+') {
			changing = true
		}
	}
}

apply plugin: 'forge'
apply plugin: 'curseforge'

def versionName = mod_version

if (project.hasProperty("mod_build_number") && !mod_build_number.isEmpty()) {
	versionName = "${mod_version}_X${mod_build_number}_H261"
	version = "[${versionName}]"
} else {
	version = mod_version
}

group = "com.hbm"
archivesBaseName = "RX-RNTM"

sourceCompatibility = 1.8
targetCompatibility = 1.8

compileJava {
	options.encoding = "UTF-8"
	sourceCompatibility = "1.8"
	targetCompatibility = "1.8"
}

minecraft {
	version = "1.7.10-10.13.4.1614-1.7.10"
	runDir = "eclipse"
}

repositories {
	maven {
		name = "ModMaven"
		url = "https://modmaven.dev"
	}

	maven {
		name = "GT"
		url = "https://gregtech.mechaenetia.com/"
	}
}

dependencies {
	/*

	 */

	compileOnly fileTree(dir: "libs/compileOnly", include: ["*.jar"])

	compileOnly "inventorytweaks:InventoryTweaks:1.59-dev:deobf"
	implementation "li.cil.oc:OpenComputers:MC1.7.10-1.5.+:api"
}

processResources {
	inputs.property "version", project.version
	inputs.property "mcversion", project.minecraft.version

	from(sourceSets.main.resources.srcDirs) {
		include "mcmod.info"

		filesMatching("mcmod.info") {
			expand([
				version: versionName,
				credits: project.hasProperty("credits") ? project.credits : ""
			])
		}
	}

	from(sourceSets.main.resources.srcDirs) {
		exclude "mcmod.info"
	}
}

jar {
	manifest {
		attributes "FMLAT": "HBM_at.cfg"
	}
}

task printVersion {
	doLast {
		println project.version
	}
}

if (Files.exists(Paths.get("curseforge.properties"))) {
	ext.cfprops = parseConfig(file("curseforge.properties"))

	curse {
		apiKey = cfprops.api_key
		projectId = cfprops.project_id
		releaseType = "release"

		displayName = "Ragex's Nuclear Tech Mod " + versionName.replace("_", "") + " for Minecraft 1.7.10"

		gameVersions.addAll([
			"Forge",
			"Java 8",
			"Client",
			"Server"
		])

		if (Files.exists(Paths.get("changelog"))) {
			changelog = String.join("\r\n", Files.readAllLines(Paths.get("changelog")))

			doLast {
				Files.move(Paths.get("changelog"), Paths.get("changelog.bak"), StandardCopyOption.REPLACE_EXISTING)
				Files.createFile(Paths.get("changelog"))
			}
		}
	}
}

static def parseConfig(File config) {
	config.withReader {
		def prop = new Properties()
		prop.load(it)
		return new ConfigSlurper().parse(prop)
	}
}
